In [1]:
%%javascript

Jupyter.keyboard_manager.command_shortcuts.add_shortcut('r', {
    help : 'run all cells',
    help_index : 'zz',
    handler : function (event) {
        IPython.notebook.execute_all_cells();
        return false;
    }}
);

In [2]:
%matplotlib inline
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
#variable="air.2m"
#variable="air.sfc"
#variable="apcp"
variable="rhum.2m"

In [4]:
# The temperature to be used for finding the viable transmission range
temperature= "air.2m"
#temperature= "air.sfc"

In [5]:
months=["01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12"]
years=range(1999, 2016)

In [6]:
# Importing WNV data
df= pd.read_csv("/Users/sparshagarwal/Downloads/WMV_data/Arbovirus_risk_modeling_US/WNV_human_cases/WNV_NI_NNI_1999to2015_prevalence_incidence_final_20180530.csv", encoding='latin-1')
df=df[df["Select_County"]==1]
df.rename(columns = {'GEOID10':'GEOID'}, inplace = True)

In [7]:
# Defining Virus tramission temperarture range(in Fahrenheit)
a=60
b=90

In [8]:
# Converting Fahrenheit to Kelvin
a=(a-32)*5/9 + 273
b=(b-32)*5/9 + 273

In [9]:
temp= pd.read_csv("/Users/sparshagarwal/Downloads/WMV_data/intersections/narr_urban_county_data_masked/" + "air.2m" +"_masked/"+ "1999" + "_" + "01" + "_masked.csv")

In [10]:
# For CDD and CP
df_mod=df.copy()
for j in years:
    for k in range(len(months)):
        #Importing monthly temperature data
        temp= pd.read_csv("/Users/sparshagarwal/Downloads/WMV_data/intersections/narr_urban_county_data_masked/" + temperature +"_masked/"+ str(j) + "_" + months[k] + "_masked.csv")
        #Importing monthly precipitation data
        prec=pd.read_csv("/Users/sparshagarwal/Downloads/WMV_data/intersections/narr_urban_county_data_masked/apcp_masked/"+ str(j) + "_" + months[k] + "_masked.csv")
        # Only considering max values
        temp=temp[["GEOID", "max"]]
        temp.rename(columns = {'max':'mean_temp_' + str(j) + "_" + months[k]}, inplace = True)
        prec=prec[["GEOID", "max"]]
        prec.rename(columns = {'max':'mean_prec_' + str(j) + "_" + months[k]}, inplace = True)
        # Adding columns corresponding to all years and months
        df_mod=df_mod.join(temp.set_index('GEOID'), on='GEOID')
        df_mod=df_mod.join(prec.set_index('GEOID'), on='GEOID')

In [11]:
df_mod_1[df_mod_1["STNAME"]== "Illinois"]

NameError: name 'df_mod_1' is not defined

In [ ]:
df_mod[df_mod["STNAME"]== "Illinois"]

In [ ]:
df_mod_2[df_mod_2["STNAME"]== "Illinois"]

In [13]:
# For CDD and CP (For max temp)
df_mod_1=df.copy()
for j in years:
    for k in range(len(months)):
        #Importing monthly temperature data
        temp= pd.read_csv("/Users/sparshagarwal/Downloads/WMV_data/intersections/narr_urban_county_data_masked/" + temperature +"_masked/"+ str(j) + "_" + months[k] + "_masked.csv")
        #Importing monthly precipitation data
        prec=pd.read_csv("/Users/sparshagarwal/Downloads/WMV_data/intersections/narr_urban_county_data_masked/apcp_masked/"+ str(j) + "_" + months[k] + "_masked.csv")
        # Only considering max values
        temp=temp[["GEOID", "max"]]
        temp.rename(columns = {'max':'mean_temp_' + str(j) + "_" + months[k]}, inplace = True)
        prec=prec[["GEOID", "max"]]
        prec.rename(columns = {'max':'mean_prec_' + str(j) + "_" + months[k]}, inplace = True)
        # Adding columns corresponding to all years and months
        df_mod_1=df_mod_1.join(temp.set_index('GEOID'), on='GEOID')
        df_mod_1=df_mod_1.join(prec.set_index('GEOID'), on='GEOID')

In [14]:
# For CDD and CP (For mean temp)
df_mod_2=df.copy()
for j in years:
    for k in range(len(months)):
        #Importing monthly temperature data
        temp= pd.read_csv("/Users/sparshagarwal/Downloads/WMV_data/intersections/narr_urban_county_data_masked/" + temperature +"_masked/"+ str(j) + "_" + months[k] + "_masked.csv")
        #Importing monthly precipitation data
        prec=pd.read_csv("/Users/sparshagarwal/Downloads/WMV_data/intersections/narr_urban_county_data_masked/apcp_masked/"+ str(j) + "_" + months[k] + "_masked.csv")
        # Only considering max values
        temp=temp[["GEOID", "mean"]]
        temp.rename(columns = {'mean':'mean_temp_' + str(j) + "_" + months[k]}, inplace = True)
        prec=prec[["GEOID", "mean"]]
        prec.rename(columns = {'mean':'mean_prec_' + str(j) + "_" + months[k]}, inplace = True)
        # Adding columns corresponding to all years and months
        df_mod_2=df_mod_2.join(temp.set_index('GEOID'), on='GEOID')
        df_mod_2=df_mod_2.join(prec.set_index('GEOID'), on='GEOID')

In [15]:
# For CDD and CP (For min temp)
df_mod_3=df.copy()
for j in years:
    for k in range(len(months)):
        #Importing monthly temperature data
        temp= pd.read_csv("/Users/sparshagarwal/Downloads/WMV_data/intersections/narr_urban_county_data_masked/" + temperature +"_masked/"+ str(j) + "_" + months[k] + "_masked.csv")
        #Importing monthly precipitation data
        prec=pd.read_csv("/Users/sparshagarwal/Downloads/WMV_data/intersections/narr_urban_county_data_masked/apcp_masked/"+ str(j) + "_" + months[k] + "_masked.csv")
        # Only considering min values
        temp=temp[["GEOID", "min"]]
        temp.rename(columns = {'min':'mean_temp_' + str(j) + "_" + months[k]}, inplace = True)
        prec=prec[["GEOID", "min"]]
        prec.rename(columns = {'min':'mean_prec_' + str(j) + "_" + months[k]}, inplace = True)
        # Adding columns corresponding to all years and months
        df_mod_3=df_mod_3.join(temp.set_index('GEOID'), on='GEOID')
        df_mod_3=df_mod_3.join(prec.set_index('GEOID'), on='GEOID')

In [19]:
#Max temp
df_mod_1

,GEOID,Select_County,STATEFP10,STATENS,STUSPS,STNAME,COUNTYFP10,COUNTYNS10,CTYNAME,POPESTIMATE1999,...,mean_temp_2015_08,mean_prec_2015_08,mean_temp_2015_09,mean_prec_2015_09,mean_temp_2015_10,mean_prec_2015_10,mean_temp_2015_11,mean_prec_2015_11,mean_temp_2015_12,mean_prec_2015_12
0,1001,1,1,1779775,AL,Alabama,1,161526,Autauga County,42963,...,300.961395,3.191014,298.020111,2.407377,292.738861,2.054975,288.904816,5.022571,287.931915,10.235910
1,1003,1,1,1779775,AL,Alabama,3,161527,Baldwin County,137555,...,301.192719,3.586679,298.426880,4.374825,293.893860,3.425691,290.196503,5.677779,289.600769,9.016909
7,1015,1,1,1779775,AL,Alabama,15,161533,Calhoun County,114910,...,299.682159,4.344239,296.762054,2.230815,291.341705,2.625792,287.456665,5.621268,286.980042,8.059500
16,1033,1,1,1779775,AL,Alabama,33,161542,Colbert County,54715,...,298.807404,5.785771,296.531067,1.504252,290.976532,2.655025,287.603516,4.660331,286.338409,8.751284
22,1045,1,1,1779775,AL,Alabama,45,161548,Dale County,49118,...,301.418793,3.218987,298.365967,5.824565,293.795074,1.524229,290.073578,7.334810,289.471985,13.657534
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3079,55131,1,55,1779806,WI,Wisconsin,131,1581125,Washington County,116131,...,294.698273,3.665308,292.807617,3.838106,284.396393,1.363695,278.986328,3.060331,275.601013,3.951133
3080,55133,1,55,1779806,WI,Wisconsin,133,1581126,Waukesha County,357829,...,295.106781,3.665308,293.078461,4.700606,284.864136,1.363695,279.273315,3.502519,275.982819,3.981879
3083,55139,1,55,1779806,WI,Wisconsin,139,1581129,Winnebago County,155801,...,294.668793,3.414300,292.635223,4.851648,284.077087,2.146709,278.672272,2.495227,275.281952,3.500528
3095,56021,1,56,1779807,WY,Wyoming,21,1605075,Laramie County,81009,...,297.413513,1.556941,294.538605,0.840711,286.851532,1.638392,277.030609,1.226998,271.252991,0.839237
3097,56025,1,56,1779807,WY,Wyoming,25,1605077,Natrona County,66282,...,296.317993,0.934461,292.762054,0.208419,285.660736,1.257848,274.048309,0.588456,268.751465,0.801435

In [20]:
#Mean temp
df_mod_2

,GEOID,Select_County,STATEFP10,STATENS,STUSPS,STNAME,COUNTYFP10,COUNTYNS10,CTYNAME,POPESTIMATE1999,...,mean_temp_2015_08,mean_prec_2015_08,mean_temp_2015_09,mean_prec_2015_09,mean_temp_2015_10,mean_prec_2015_10,mean_temp_2015_11,mean_prec_2015_11,mean_temp_2015_12,mean_prec_2015_12
0,1001,1,1,1779775,AL,Alabama,1,161526,Autauga County,42963,...,300.446899,2.954559,297.675323,1.813757,292.477722,1.996192,288.642914,4.548873,287.663086,8.428452
1,1003,1,1,1779775,AL,Alabama,3,161527,Baldwin County,137555,...,301.012909,3.304862,298.282288,4.138302,293.602905,3.254824,289.915466,5.225370,289.157837,8.089489
7,1015,1,1,1779775,AL,Alabama,15,161533,Calhoun County,114910,...,299.412476,3.923457,296.494344,1.853211,290.953573,2.310519,287.068115,5.240886,286.656799,7.988515
16,1033,1,1,1779775,AL,Alabama,33,161542,Colbert County,54715,...,298.384094,5.190383,296.089783,1.037781,290.533875,2.543823,287.024567,4.372962,285.906647,7.168118
22,1045,1,1,1779775,AL,Alabama,45,161548,Dale County,49118,...,301.194885,2.829245,298.141754,4.270658,293.485352,1.270638,289.638763,7.008638,288.978699,11.500464
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3079,55131,1,55,1779806,WI,Wisconsin,131,1581125,Washington County,116131,...,294.612335,3.539804,292.721436,3.785893,284.236755,1.342652,278.829285,2.777779,275.441467,3.561389
3080,55133,1,55,1779806,WI,Wisconsin,133,1581126,Waukesha County,357829,...,294.970622,2.955967,292.988200,4.354947,284.708211,1.311192,279.177653,3.326217,275.855550,3.905014
3083,55139,1,55,1779806,WI,Wisconsin,139,1581129,Winnebago County,155801,...,294.476562,2.837561,292.489380,4.248393,283.712280,1.757785,278.464539,2.193274,274.872986,3.238746
3095,56021,1,56,1779807,WY,Wyoming,21,1605075,Laramie County,81009,...,295.266561,0.991039,292.685140,0.343705,285.473592,1.465971,275.299011,0.885483,270.457845,0.617673
3097,56025,1,56,1779807,WY,Wyoming,25,1605077,Natrona County,66282,...,295.209527,0.519419,291.609185,0.137933,284.705811,0.743511,272.651015,0.508016,267.546549,0.472106

In [21]:
#Min temp
df_mod_3

,GEOID,Select_County,STATEFP10,STATENS,STUSPS,STNAME,COUNTYFP10,COUNTYNS10,CTYNAME,POPESTIMATE1999,...,mean_temp_2015_08,mean_prec_2015_08,mean_temp_2015_09,mean_prec_2015_09,mean_temp_2015_10,mean_prec_2015_10,mean_temp_2015_11,mean_prec_2015_11,mean_temp_2015_12,mean_prec_2015_12
0,1001,1,1,1779775,AL,Alabama,1,161526,Autauga County,42963,...,299.942474,2.391618,297.179749,1.391492,292.086914,1.905025,288.262390,4.190279,287.410492,7.249016
1,1003,1,1,1779775,AL,Alabama,3,161527,Baldwin County,137555,...,300.882263,3.156991,298.069336,3.802429,293.042816,2.784562,289.389465,4.772831,288.367889,7.583945
7,1015,1,1,1779775,AL,Alabama,15,161533,Calhoun County,114910,...,298.945496,3.531235,296.006317,1.528211,290.341187,1.914350,286.543121,4.753300,286.332611,7.950124
16,1033,1,1,1779775,AL,Alabama,33,161542,Colbert County,54715,...,297.958099,4.361376,295.647461,0.861804,290.058441,2.237939,286.572540,3.963456,285.532471,5.056979
22,1045,1,1,1779775,AL,Alabama,45,161548,Dale County,49118,...,300.874451,2.494189,297.953705,2.741231,293.219208,1.068332,289.324097,6.596529,288.539764,8.869984
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3079,55131,1,55,1779806,WI,Wisconsin,131,1581125,Washington County,116131,...,294.526398,3.414300,292.635223,3.733679,284.077087,1.321608,278.672272,2.495227,275.281952,3.171647
3080,55133,1,55,1779806,WI,Wisconsin,133,1581126,Waukesha County,357829,...,294.698273,2.568282,292.807617,3.838106,284.396393,1.262888,278.986328,3.060331,275.601013,3.782030
3083,55139,1,55,1779806,WI,Wisconsin,139,1581129,Winnebago County,155801,...,294.315216,2.366417,292.353699,3.733679,283.441254,1.321608,278.299347,1.878821,274.581116,2.940044
3095,56021,1,56,1779807,WY,Wyoming,21,1605075,Laramie County,81009,...,290.840424,0.680177,288.234955,0.132898,282.092957,1.315056,271.338165,0.591841,267.625977,0.448864
3097,56025,1,56,1779807,WY,Wyoming,25,1605077,Natrona County,66282,...,294.008759,0.402203,290.522980,0.078992,283.889313,0.422667,271.532166,0.390539,266.267090,0.239943

In [22]:
##### ends here

In [ ]:
# Adding a column for incident year
incident_year=[2015 for i in range(len(df_mod))]
for j in range(len(df_mod)):
    for i in years:
        if(df_mod.iloc[j]["NI_IR_" + str(i)]!=0):
            incident_year[j]=i
            break
df_mod["Incident_year"]=incident_year

In [ ]:
x_cdd=[]    #For storing cumulative degree days  
x_cp=[]     #For storing cumulative precipitation
y=[]        #For storing IR of WNV
for i in years:
    #Number of days in february
    feb=28
    #For leap year
    if(i%4==0):
        feb=29
    #Months with number of days
    days={"01":31, "02":feb, "03" :31, "04":30, "05":31, "06":30, "07":31, "08":31, "09":30, "10":31, "11":30, "12":31}
    for j in range(len(df_mod)):
        cdd=0
        cp=0
        # For all years after first incident year
        if(df_mod.iloc[j]["Incident_year"]<i):
            for k in months:
                if(df_mod.iloc[j]["mean_temp_" + str(i) + "_" + k]>=a and df_mod.iloc[j]["mean_temp_" + str(i) + "_" + k]<=b):
                    cdd=cdd + days[k]
                    cp=cp + df_mod.iloc[j]["mean_prec_" + str(i) + "_" + k]
            x_cdd.append(cdd)
            x_cp.append(cp)
            y.append(df_mod.iloc[j]["NI_IR_" + str(i)])

In [ ]:
df_cdd=pd.DataFrame()
df_cp=pd.DataFrame()
df_cdd["IR"]=y
df_cdd["CDD"]=x_cdd
df_cp["IR"]=y
df_cp["CP"]=x_cp

In [ ]:
df_cdd.plot(kind='scatter',x='CDD',y='IR',color='red')

In [ ]:
df_cp.plot(kind='scatter',x='CP',y='IR',color='red')

In [ ]:
# For plotting standard deviations of the variable
df_mod=df.copy()
for j in years:
    for k in range(len(months)):
        #Importing monthly temperature data
        temp= pd.read_csv("/Users/sparshagarwal/Downloads/WMV_data/intersections/narr_urban_county_data_masked/" + temperature +"_masked/"+ str(j) + "_" + months[k] + "_masked.csv")
        #Importing monthly data for the variable
        var=pd.read_csv("/Users/sparshagarwal/Downloads/WMV_data/intersections/narr_urban_county_data_masked/" + variable +"_masked/"+ str(j) + "_" + months[k] + "_masked.csv")
        # Only considering mean values
        temp=temp[["GEOID", "mean"]]
        temp.rename(columns = {'mean':'mean_temp_' + str(j) + "_" + months[k]}, inplace = True)
        var=var[["GEOID", "mean"]]
        var.rename(columns = {'mean':'mean_' + str(j) + "_" + months[k]}, inplace = True)
        # Adding columns corresponding to all years and months
        df_mod=df_mod.join(temp.set_index('GEOID'), on='GEOID')
        df_mod=df_mod.join(var.set_index('GEOID'), on='GEOID')

In [ ]:
# Adding a column for incident year
incident_year=[2015 for i in range(len(df_mod))]
for j in range(len(df_mod)):
    for i in years:
        if(df_mod.iloc[j]["NI_IR_" + str(i)]!=0):
            incident_year[j]=i
            break
df_mod["Incident_year"]=incident_year

In [ ]:
x=[]        #For storing temperature/precipitation/humidity standard deviation 
y=[]        #For storing IR of WNV
for i in years:
    for j in range(len(df_mod)):
        temp_list=[]
        # For all years after first incident year
        if(df_mod.iloc[j]["Incident_year"]<i):
            if(df_mod.iloc[j]["NI_IR_" + str(i)]>0):     #Removing IR=0 instances
                for k in months:
                    if(df_mod.iloc[j]["mean_temp_" + str(i) + "_" + k]>=a and df_mod.iloc[j]["mean_temp_" + str(i) + "_" + k]<=b):
                        temp_list.append(df_mod.iloc[j]["mean_" + str(i) + "_" + k])
                if(len(temp_list)>0):
                        x.append(np.std(temp_list))
                        y.append(df_mod.iloc[j]["NI_IR_" + str(i)])

In [ ]:
df_std=pd.DataFrame()
df_std["IR"]=y
df_std["Std"]=x

In [ ]:
df_std.plot(kind='scatter',x='Std',y='IR',color='red', title= variable)

In [ ]:
df_mod[df_mod["STNAME"]=="Michigan"]

In [ ]:
#Below section is for verification of NARR data, done by plotting monthly temperatures for different counties.

In [ ]:
#new=df_mod[df_mod["CTYNAME"]== "Pinal County"]

In [ ]:
#new=df_mod[df_mod["CTYNAME"]== "New York County"]

In [ ]:
#new=df_mod[df_mod["CTYNAME"]== "Champaign County"]

In [ ]:
county="San Francisco County"

In [ ]:
new=df_mod[df_mod["CTYNAME"]== county]

In [ ]:
temp_dict={}

for i in years:
    temp=[]
    for j in months:
        temp.append((new.iloc[0]["mean_temp_" + str(i) + "_" + j] -273)*9/5 +32)
    temp_dict[i]=temp
    
month=[]
for j in months:
    month.append(int(j))

In [ ]:
for i in years:
    plt.plot(month, temp_dict[i])
plt.xlabel("Month")
plt.ylabel("Temp (F)")
plt.title(county)

In [ ]:
df