In [70]:
#Importing the necessary packages
import pandas as pd
import numpy as np
import glob
import time

In [71]:
wnv = pd.read_csv("WNV_NI_NNI_1999to2015_prevalence_incidence_final_20180530.csv", encoding="ISO-8859-1")
print("Shape of the Dataframe: ", wnv.shape, "\n")
print(list(wnv.columns), "\n")
wnv.head(5)

Shape of the Dataframe:  (3108, 153)

['GEOID10', 'Select_County', 'STATEFP10', 'STATENS', 'STUSPS', 'STNAME', 'COUNTYFP10', 'COUNTYNS10', 'CTYNAME', 'POPESTIMATE1999', 'POPESTIMATE2000', 'POPESTIMATE2001', 'POPESTIMATE2002', 'POPESTIMATE2003', 'POPESTIMATE2004', 'POPESTIMATE2005', 'POPESTIMATE2006', 'POPESTIMATE2007', 'POPESTIMATE2008', 'POPESTIMATE2009', 'POPESTIMATE2010', 'POPESTIMATE2011', 'POPESTIMATE2012', 'POPESTIMATE2013', 'POPESTIMATE2014', 'POPESTIMATE2015', 'Note', 'CDC_WNV_Record', 'CDC_NI_Record', 'CDC_NNI_Record', 'NI_Total', 'Years_with_NI', 'NI_1999', 'NI_2000', 'NI_2001', 'NI_2002', 'NI_2003', 'NI_2004', 'NI_2005', 'NI_2006', 'NI_2007', 'NI_2008', 'NI_2009', 'NI_2010', 'NI_2011', 'NI_2012', 'NI_2013', 'NI_2014', 'NI_2015', 'NNI_Total', 'Years_with_NNI', 'NNI_1999', 'NNI_2000', 'NNI_2001', 'NNI_2002', 'NNI_2003', 'NNI_2004', 'NNI_2005', 'NNI_2006', 'NNI_2007', 'NNI_2008', 'NNI_2009', 'NNI_2010', 'NNI_2011', 'NNI_2012', 'NNI_2013', 'NNI_2014', 'NNI_2015', 'CDC_WNV_note', 'NI_IR_1999', 'NI_IR_2000', 'NI_IR_2001', 'NI_IR_2002', 'NI_IR_2003', 'NI_IR_2004', 'NI_IR_2005', 'NI_IR_2006', 'NI_IR_2007', 'NI_IR_2008', 'NI_IR_2009', 'NI_IR_2010', 'NI_IR_2011', 'NI_IR_2012', 'NI_IR_2013', 'NI_IR_2014', 'NI_IR_2015', 'MEAN_ANNUAL_IR_ESTAB', 'CUM_IR_1999to2015', 'MEAN_ANNUAL_IR_1999to2015', 'MEAN_ANNUAL_IR_1999to2004', 'MEAN_ANNUAL_IR_2005to2015', 'MEAN_ANNUAL_IR_2006to2015', 'NI_Total_2006to2015', 'NI_Total_2005to2015', 'ST_ABBREV', 'NAMELSAD10', 'POP_URBAN', 'POPPCT_URB', 'AREA_URBAN', 'AREAPCT_UR', 'POPDEN_URB', 'POP_RURAL', 'POPPCT_RUR', 'AREA_RURAL', 'AREAPCT_RU', 'POPDEN_RUR', 'DeG12Region', 'NCHS_2013', 'NCHS_2006', 'NCHS_1990', 'NCHS_2013_3class', 'Total_BG.sBG', 'PCT_CTYPOP_sBG', 'Year_1st_NI_case', 'Year_1st_NNI_case', 'NI_NNI_DIFF', 'Establish_2000', 'Establish_2001', 'Establish_2002', 'Establish_2003', 'Establish_2004', 'Establish_2005', 'Establish_2006', 'Establish_2007', 'Establish_2008', 'Establish_2009', 'Establish_2010', 'Establish_2011', 'Establish_2012', 'Establish_2013', 'Establish_2014', 'Establish_2015', 'NIIR_2000_Z', 'NIIR_2001_Z', 'NIIR_2002_Z', 'NIIR_2003_Z', 'NIIR_2004_Z', 'NIIR_2005_Z', 'NIIR_2006_Z', 'NIIR_2007_Z', 'NIIR_2008_Z', 'NIIR_2009_Z', 'NIIR_2010_Z', 'NIIR_2011_Z', 'NIIR_2012_Z', 'NIIR_2013_Z', 'NIIR_2014_Z', 'NIIR_2015_Z', 'NIIR_EST_AVG_Z', 'NIIR_EST_MED_Z', 'County_WNV_Class', 'County_WNV_Class2', 'filter_$']

,GEOID10,Select_County,STATEFP10,STATENS,STUSPS,STNAME,COUNTYFP10,COUNTYNS10,CTYNAME,POPESTIMATE1999,...,NIIR_2011_Z,NIIR_2012_Z,NIIR_2013_Z,NIIR_2014_Z,NIIR_2015_Z,NIIR_EST_AVG_Z,NIIR_EST_MED_Z,County_WNV_Class,County_WNV_Class2,filter_$
0,1001,1,1,1779775,AL,Alabama,1,161526,Autauga County,42963,...,-.172668378274114,-.313041876784145,-.237005866057391,-.211466937746909,-.197767338621807,-.230659201920693,-.231569016088473,2,NI-S,0
1,1003,1,1,1779775,AL,Alabama,3,161527,Baldwin County,137555,...,-.172668378274114,.0148439683883608,-.177634573907632,-.211466937746909,-.197767338621807,-.177866829768146,-.186748999098691,4,NI-M-pre12,0
2,1005,0,1,1779775,AL,Alabama,5,161528,Barbour County,28866,...,-.172668378274114,-.313041876784145,-.237005866057391,-.211466937746909,-.197767338621807,-.220130592240443,-.221517976917691,2,NI-S-NNI,0
3,1007,0,1,1779775,AL,Alabama,7,161529,Bibb County,20560,...,,,,,,,,3,NI-S,0
4,1009,0,1,1779775,AL,Alabama,9,161530,Blount County,50237,...,,,,,,,,1,NNI-S,0

In [72]:
wnv = wnv[wnv['Select_County'] == 1]
print("Shape of the DataFrame now: ", wnv.shape)

#df2 = wnv[["GEOID10", "CTYNAME", "STUSPS"]]
#df2.insert(1, 'YEAR', '1999')
#df2.loc[:,'POPESTIMATE'] = wnv['POPESTIMATE1999']

df = pd.DataFrame(columns = ['YEAR','GEOID10','CTYNAME','STUSPS','DeG12Region','Total_BG.sBG','County_WNV_Class','County_WNV_Class2','POPESTIMATE','NI_','NNI_','NI_IR_', 'Establish_', 'NIIR_Z'])

#### df = pd.DataFrame(columns = ['YEAR','GEOID10','CTYNAME','STUSPS','DeG12Region', 'Total_BG.sBG','County_WNV_Class','County_WNV_Class2', 'POPESTIMATE', 'NI_', 'NNI_', 'NI_IR_', 'Establish_','NIIR_Z', CDC_WNV_Record', 
####     'CDC_NI_Record', 'CDC_NNI_Record', 'NI_Total', 'Years_with_NI', 'NNI_Total', 'Years_with_NNI', 'MEAN_ANNUAL_IR_ESTAB',
####     'CUM_IR_1999to2015', 'MEAN_ANNUAL_IR_1999to2015', 'POPPCT_URB', 'AREA_URBAN', 'POPPCT_RUR', 'AREA_RURAL',
####     'AREAPCT_RU', 'NIIR_EST_AVG_Z', 'NIIR_EST_MED_Z'])


year_list = ['1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007',
                '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015' ]

Shape of the DataFrame now:  (852, 153)

In [73]:
for  year in year_list:
    
    temp_df = pd.DataFrame(columns = ['POPESTIMATE'])
    
    POP = 'POPESTIMATE' + year
    temp_df.loc[:,'POPESTIMATE'] = wnv[POP]
    
    NI = 'NI_' + year
    temp_df.loc[:,'NI_'] = wnv[NI]
    
    NNI = 'NNI_' + year
    temp_df.loc[:,'NNI_'] = wnv[NNI]
    
    NI_IR = 'NI_IR_' + year
    temp_df.loc[:,'NI_IR_'] = wnv[NI_IR]
    
    if (year == '1999'): 
        temp_df.loc[:,'Establish_'] = 0
        temp_df.loc[:,'NIIR_Z'] = 0

    else:
        Establish = 'Establish_' + year
        temp_df.loc[:,'Establish_'] = wnv[Establish]
        
        NIIR_Z = 'NIIR_' + year + '_Z'
        temp_df.loc[:,'NIIR_Z'] = wnv[NIIR_Z]
    
    temp_df.insert(0, 'YEAR', year)
    
    #Common for each temp_df
    temp_df.insert(1, 'GEOID10', wnv['GEOID10'])
    temp_df.insert(2, 'CTYNAME', wnv['CTYNAME'])
    temp_df.insert(3, 'STUSPS', wnv['STUSPS'])
    temp_df.insert(4, 'DeG12Region', wnv['DeG12Region'])
    temp_df.insert(5, 'Total_BG.sBG', wnv['Total_BG.sBG'])
    temp_df.insert(6, 'County_WNV_Class', wnv['County_WNV_Class'])
    temp_df.insert(7, 'County_WNV_Class2', wnv['County_WNV_Class2'])
       
    
    ####temp_df.insert(14, 'CDC_WNV_Record', wnv['CDC_WNV_Record'])
    ####temp_df.insert(15, 'CDC_NI_Record', wnv['CDC_NI_Record'])
    ####temp_df.insert(16, 'CDC_NNI_Record', wnv['CDC_NNI_Record'])
    ####temp_df.insert(17, 'NI_Total', wnv['NI_Total'])
    ####temp_df.insert(18, 'Years_with_NI', wnv['Years_with_NI'])
    ####temp_df.insert(19, 'NNI_Total', wnv['NNI_Total'])
    ####temp_df.insert(20, 'Years_with_NNI', wnv['Years_with_NNI'])
    ####temp_df.insert(21, 'MEAN_ANNUAL_IR_ESTAB', wnv['MEAN_ANNUAL_IR_ESTAB'])
    ####temp_df.insert(22, 'CUM_IR_1999to2015', wnv['CUM_IR_1999to2015'])
    ####temp_df.insert(23, 'MEAN_ANNUAL_IR_1999to2015', wnv['MEAN_ANNUAL_IR_1999to2015'])
    ####temp_df.insert(24, 'POPPCT_URB', wnv['POPPCT_URB'])
    ####temp_df.insert(25, 'AREA_URBAN', wnv['AREA_URBAN'])
    ####temp_df.insert(26, 'AREAPCT_UR', wnv['AREAPCT_UR'])
    ####temp_df.insert(27, 'POPPCT_RUR', wnv['POPPCT_RUR'])
    ####temp_df.insert(28, 'AREA_RURAL', wnv['AREA_RURAL'])
    ####temp_df.insert(29, 'AREAPCT_RU', wnv['AREAPCT_RU'])
    ####temp_df.insert(30, 'NIIR_EST_AVG_Z', wnv['NIIR_EST_AVG_Z'])
    ####temp_df.insert(31, 'NIIR_EST_MED_Z', wnv['NIIR_EST_MED_Z'])

    df = df.append(temp_df, ignore_index=True)

In [75]:
print(df.shape)
df.head(5)

(14484, 14)

,YEAR,GEOID10,CTYNAME,STUSPS,DeG12Region,Total_BG.sBG,County_WNV_Class,County_WNV_Class2,POPESTIMATE,NI_,NNI_,NI_IR_,Establish_,NIIR_Z
0,1999,1001,Autauga County,AL,2,15,2,NI-S,42963,0,0,0.0,0,0
1,1999,1003,Baldwin County,AL,2,28,4,NI-M-pre12,137555,0,0,0.0,0,0
2,1999,1015,Calhoun County,AL,2,45,2,NI-S-NNI,114910,0,0,0.0,0,0
3,1999,1033,Colbert County,AL,2,24,1,none,54715,0,0,0.0,0,0
4,1999,1045,Dale County,AL,2,10,2,NI-S-NNI,49118,0,0,0.0,0,0

In [ ]:
# Not sure what these columns are; 
#### 1. Note - Only one row has data, so dropping it
#### 2. CDC_WNV_Record, CDC_NI_Record, CDC_NNI_Record and a few more - 
####     - Doesn't make any sense repeating these data values for each year
#### 3. CDC_WNV_note - No data
#### 4. MEAN_ANNUAL_IR_1999to2004, MEAN_ANNUAL_IR_2005to2015, MEAN_ANNUAL_IR_2006to2015, NI_Total_2006to2015,
####   'NI_Total_2005to2015' - The combined data of these columns have been added
#### 5. 'ST_ABBREV', 'NAMELSAD10' - Dropping repeated columns
#### 6. 'POP_URBAN', 'POP_RURAL' - Do we need this? We have population columns already
#### 7. POPDEN_URB, POPDEN_RUR - Dropping density columns
#### 8. 'NCHS_2013', 'NCHS_2006', 'NCHS_1990', 'NCHS_2013_3class' -> Do we need these? Its only for specific years
#### 9. PCT_CTYPOP_sBG, NI_NNI_DIFF, filter_$ -> What is this? Do we need it?


#### 10. Year_1st_NI_case, Year_1st_NNI_case -> Should we remove all the rows for those counties before the first year?